### PR TITLE
Update test-runner.yaml

### PR DESCRIPTION
**Pull request by tehmoon**
Add namespace to the tester and force restart it if failing.

### CODE REVIEW

**Comment by tehmoon** [comment]
Hi @ishustava.
Thank you for following up!

I also changed the `restartPolicy` because using this chart with `helm template` and applying the result to kubernetes directly, I saw that the tester pod was actually being scheduled right away, before the consul pods, making in fail right away.

If that blocks your pipeline, let me know and I'll remove it.

**Comment by lkysow** [comment]
If using helm template, we recommend running with

```
tests:
  enabled: false
```

We added that just for helm template.

**Comment by tehmoon** [comment]
Hi @lkysow,

Yes that's what I'm doing but if one wants to starts the tests, it does not work if using a namespace.
Alternatively, it works if kustomize sets the namespace on top of `helm3 template`.

**Comment by ishustava** [comment]
Hey @tehmoon, if you don't mind removing the `restartPolicy` change (based on what @lkysow said), I can approve your PR. The namespace change looks good.

**Comment by tehmoon** [comment]
@ishustava Done!! Thank you so much for the follow up.

**Comment by ishustava** [comment]
Thank you for making the change @tehmoon and for the PR!

**Pull request merged**
