### PR TITLE
Fix eks cleanup aws creds

### PR DESCRIPTION
**Pull request by lkysow**
Should fix https://app.circleci.com/pipelines/github/hashicorp/consul-helm/3384/workflows/619305fc-9306-4298-b48b-e27738aef169/jobs/15030

Tested it works with https://app.circleci.com/pipelines/github/hashicorp/consul-helm/3391/workflows/7e51cba6-7e19-4762-80e5-0279e8571736/jobs/15081

### CODE REVIEW

**Review by ishustava — APPROVED** [review]
Looks good.

I'm curious if the original way didn't work because we also need to tell AWS Go SDK to load the config file, as described [here](https://github.com/aws/aws-sdk-go/blob/d1c997498fd43019b43d52fcd74e402e16630636/aws/session/session.go#L74-L78).

BTW, originally we configured AWS the way we did because by default the `AWS_SESSION_TOKEN` is only valid for 1hr, and so these creds would expire by the time acceptance tests would finish. I don't think this job would take as long, and so this approach should work.

**Review by sadjamz — APPROVED** [review]
Very good.

I am curious as to whether the AWS Go SDK actually looks up and uses the 'AWS_ACCESS_KEY_ID' or 'AWS_SECRET_ACCESS_KEY' environment variables. Tried searching for that but couldn't find it. But it must right?

**Comment by lkysow** [comment]
I think you have to do something special to get it to assume role (https://aws.amazon.com/blogs/developer/assume-aws-iam-roles-with-mfa-using-the-aws-sdk-for-go/). The below did not work:

```
circleci@01c6aa652c32:~/project/hack/aws-acceptance-test-cleanup$ go run ./...
Error: AccessDeniedException:
	status code: 403, request id: ebb6822b-9352-47d7-9f11-a304f0f5b7ea
exit status 1
circleci@01c6aa652c32:~/project/hack/aws-acceptance-test-cleanup$ env |grep AWS_SDK_LOAD_CONFIG
circleci@01c6aa652c32:~/project/hack/aws-acceptance-test-cleanup$ export AWS_SDK_LOAD_CONFIG=true
circleci@01c6aa652c32:~/project/hack/aws-acceptance-test-cleanup$ go run ./...
Error: AccessDeniedException:
	status code: 403, request id: 52229248-b546-40f8-a1ca-f25ccdb04222
exit status 1
circleci@01c6aa652c32:~/project/hack/aws-acceptance-test-cleanup$ env|grep AWS
AWS_ROLE_ARN=arn:aws:iam::xxxxxxxxxx:role/service-circleci-consul-helm-tests
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxx
AWS_ACCESS_KEY_ID=xxxxxxxxxxxx
AWS_SDK_LOAD_CONFIG=true
circleci@01c6aa652c32:~/project/hack/aws-acceptance-test-cleanup$ export AWS_PROFILE=helm_user
circleci@01c6aa652c32:~/project/hack/aws-acceptance-test-cleanup$ go run ./...
Error: AccessDeniedException:
	status code: 403, request id: 1c5b61ee-c7f1-428f-8b77-482bedd28dcb
exit status 1
```

**Comment by lkysow** [comment]
> I am curious as to whether the AWS Go SDK actually looks up and uses the 'AWS_ACCESS_KEY_ID' or 'AWS_SECRET_ACCESS_KEY' environment variables. Tried searching for that but couldn't find it. But it must right?

Looks like its from https://github.com/aws/aws-sdk-go/blob/main/aws/session/env_config.go#L274.

**Comment by lkysow** [comment]
Thanks @sadjamz and @ishustava I couldn't get this working any other way so gonna merge this.

**Pull request merged**
