### PR TITLE
Tests are now optional

### PR DESCRIPTION
**Pull request by michaelgeorgeattard**
Tests can be toggled off to avoid changes across installations using https://github.com/roboll/helmfile and similar tools.

Alternatively, https://github.com/hashicorp/consul-helm/pull/143

(This is the safer option)

### CODE REVIEW

**Comment by oceyral** [comment]
Pretty much must-have, since the test pod cannot be created PodSecurityPolicies are activated (the test pod doesn't have one, or a service account).

**Comment by lkysow** [comment]
> Pretty much must-have, since the test pod cannot be created when PodSecurityPolicies are activated (the test pod doesn't have one, or a service account).

This is only created when you purposefully run `helm test` though right?

**Comment by lkysow** [comment]
Closed by #143.

@oceyral if you can help me understand better why this is necessary then I can reopen!

**Comment by oceyral** [comment]
@lkysow They are also generated with `helm template`. In our case, we are not using tiller, but the output of helm template.

I did not remember about them only being generated through `helm test` so it is less of an issue than I thought, but still nice to have.

**Comment by lkysow** [comment]
> @lkysow They are also generated with `helm template`. In our case, we are not using tiller, but the output of helm template.
> 
> I did not remember about them only being generated through `helm test` so it is less of an issue than I thought, but still nice to have.

Ahh I understand. Yes it looks like using `helm template` causes it to be generated. I'll re-open.

**Pull request closed without merging**
