### PR TITLE
Feature/client host networking

### PR DESCRIPTION
**Pull request by kieranajp**
Hi,

After running into the issue described in #327, I added the workaround from that comment thread, which works perfectly.

Please let me know if this needs anything more from me.

Cheers,
--Kieran

### CODE REVIEW

**Comment by david-yu** [comment]
Hi @kieranajp thanks for the PR. I'm curious to know if you're also using Cilium, and if you're using DigitalOcean perhaps as your cloud provider?

**Comment by kieranajp** [comment]
You got it in one!

**Comment by kschoche** [comment]
This issue was resolved and merged in #496 and should be available in helm release 0.22, thank you!

**Comment by kieranajp** [comment]
@kschoche That's amazing, thank _you_! :heart:

**Pull request closed without merging**
