### PR TITLE
update DaemonSet to use host network

### PR DESCRIPTION
**Pull request by jipperinbham**
addresses https://github.com/hashicorp/consul-helm/issues/43

### CODE REVIEW

**Comment by mitchellh** [comment]
Hey @jipperinbham, thanks. I am kind of curious why this is necessary as its not super clear to me.

I've previously understood `hostNetwork` as exposing the host network interfaces into the pod. However, we use `hostPort` instead which should only expose a _single port_ and bind it to the host IP. These two seem to be separate functionality, and I'm not sure why we want the former.

The Kubernetes networking model[1] also states that all containers should be able to communicate to their nodes (and vice versa) without NAT, point 2. We tested this daemonset on a variety of K8S installations and found it to work without issue, without this change.

So my question is: why isn't port 8500 properly binding and accessible to the host IP by setting `hostPort` alone? Why is `hostNetwork` necessary as well? 

[1]: https://kubernetes.io/docs/concepts/cluster-administration/networking/#kubernetes-model

**Comment by mitchellh** [comment]
Yes, I think that'd be acceptable. Thanks for digging into this.

I'm curious if `hostNetwork` is more broadly supported than `hostPort`. If so, then just using `hostNetwork` by default might make sense too. But let's cross that bridge a different time. A toggle for now would be great.

**Comment by jipperinbham** [comment]
Ok, I've updated the PR to make `hostNetwork` be opt-in.

As far as the use of `hostNetwork` in the broader sense, IMO, the use case of running a DaemonSet where you want the Pod to be accessible over a defined port(s) is when it's typically used. I did a [naive search](https://github.com/helm/charts/search?p=3&q=hostNetwork+%26%26+DaemonSet&unscoped_q=hostNetwork+%26%26+DaemonSet) of the main helm charts repo but it's hard to say one way or another if it's used more broadly in the community.

**Comment by Art3mK** [comment]
`hostPort` works ok for me on EKS with VPC CNI. They have added `hostPort` support recently, see 
aws/amazon-vpc-cni-k8s/pull/153

**Comment by adilyse** [comment]
Following up on this-- @jipperinbham, does the fix @Art3mK mentioned make the current `hostPort` implementation work for you?

**Comment by jipperinbham** [comment]
I haven't been able to test it but good to know it's likely fixed. Since this is an "opt-in" change, is it an issue to make it an option?

**Comment by adilyse** [comment]
In an effort to keep the helm chart understandable and easy to use, we'd like to be judicious about which configuration values we add. If your underlying issue has been solved by AWS, I would prefer not to add this option at this point in time. 

If things change in the future, we can always revisit that decision.

**Comment by sunadm** [comment]
#194

**Comment by jipperinbham** [comment]
Closed this one since it's quite out of date and I can't really sign the CLA for these changes at this point.

**Pull request closed without merging**
