### PR TITLE
Delete grafana from the helm chart

### PR DESCRIPTION
**Pull request by thisisnotashwin**
Changes proposed in this PR:
- The latest grafana version has updated it's licence to AGPL and we are not bundling it along with the helm chart for Consul

How I expect reviewers to test this PR: Code review

Checklist:
- [ ] Bats tests added
- [ ] CHANGELOG entry added (*HashiCorp engineers only, community PRs should not add a changelog entry*)

### CODE REVIEW

**Review by ishustava — APPROVED** [review]
😭

**Review by david-yu — APPROVED** [review]
Sad to see this go :sadpanda:, however we will continue to provide this experience through our Learn Guide as a walkthrough for using Grafana.

**Review by kschoche — APPROVED** [review]
😿

**Comment by lkysow** [comment]
> hence support for it is being discontinued.

This is not fully accurate. We still have support for it, just not bundling it in our install.

**Comment by thisisnotashwin** [comment]
> We still have support for it, just not bundling it in our install.

That is a good point. Updated the comment!

**Pull request merged**
