### PR TITLE
Add ingress support for ui and embedded the gossip secret creation

### PR DESCRIPTION
**Pull request by disaster37**
- Add ingress support for ui with or without tls.
- Add gossip key creation as secret to avoid to create it manually.

### CODE REVIEW

**Comment by disaster37** [comment]
Hum,

I just look that I also need to update `client-daemonset.yaml` fot gossip enhance. I will fix that tomorrow.

**Comment by den-is** [comment]
Will be good to have similar ingress option:
More and more clusters are v1.16+
https://github.com/helm/charts/pull/22106
```
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
```

**Comment by thecosmicfrog** [comment]
@lkysow @disaster37 Is there any update around reviewing/merging this change? These are two important features for us in order to support Consul :)

**Comment by t-eckert** [comment]
Thank you for your pull request! The contents of this repository have been merged into [`hashicorp/consul-k8s`](https://github.com/hashicorp/consul-k8s) under the `charts/consul` directory. Please follow the instructions [here](https://github.com/hashicorp/consul-helm/issues/1051) to migrate your pull request to the `consul-k8s` repository.
This PR will now be closed and the `consul-helm` repository archived to avoid confusion between the old and new repositories.

**Pull request closed without merging**
