### PR TITLE
Bump consul-k8s and consul versions.

### PR DESCRIPTION
**Pull request by lkysow**
Bump consul to 1.8.0, consul-k8s to ~1.16.0~ => 0.16.0. Remove experimental warning
on federation. Bump chart to 0.22.0.

### CODE REVIEW

**Review by thisisnotashwin — APPROVED** [review]
Took some serious testing, but it looks great 😉

**Comment by adilyse** [comment]
Consul-k8s `1.16.0` 😱

**Comment by ashwin-venkatesh** [comment]
> Consul-k8s `1.16.0` 😱

I panicked and thought that was in the templates..took me a second to realize it was in the PR comment 😌

**Comment by lkysow** [comment]
force-pushed to update commit comment 1.16.0 => 0.16.0. The code didn't change though.

**Comment by lkysow** [comment]
@adilyse is this okay to merge?

**Review by adilyse — APPROVED** [review]

**Pull request merged**
