### PR TITLE
Allows to add annotations on the client service account ressource

### PR DESCRIPTION
**Pull request by kri5**
Regarding the issue #235 , This PR allows users to provide annotations for the client service account (It seems to be the only relevant place to support this, at least for now).

If you have any comments, feel free!

### CODE REVIEW

**Comment by kri5** [comment]
Is there any changes required/blocking this PR from being merged?

Feel free to comment :)

**Comment by lkysow** [comment]
Hi @kri5, we've got a lot of reviews in the backlog. We'll get to this asap.

**Comment by jtcressy** [comment]
@kri5 Would it be possible to expand this to the other service accounts deployed by this chart? For example, the snapshot agent service account can use this to receive credentials for object storage to backup snapshots.

**Comment by kri5** [comment]
@jtcressy I updated the PR in regards of your comments.

There are some service accounts that are attached to pods that do not have a proper entry in the values.yaml file.

Some service accounts shares annotations configurations in my PR, but feel free to comment.

**Comment by zachfeldman-koneksahealth** [comment]
is there any status update for this PR? I'd really like to see this feature merged in!

**Comment by cooperbenson-qz** [comment]
I'd also really like to see this feature merged too. @kri5 any chance you'd be willing to fix the conflicts? Otherwise I can re-open the PR with them fixed

**Comment by reza-koneksahealth** [comment]
would love to see this feature merged in. any eta on this?

**Comment by ndhanushkodi** [comment]
@cooperbenson-qz If you're able to follow up and fixup this PR that would be excellent! If you are able to make the updates, can you also add test cases for when the annotations are set as well? I can follow up with a review/merge when that's ready. Thanks!

If you don't have the bandwidth I'll plan to follow up on this at the end of the week. @reza-koneksahealth @zachfeldman-koneksahealth

**Comment by cooperbenson-qz** [comment]
Thanks @ndhanushkodi. I should have some time for this tomorrow, but I'll update the thread either way.

**Comment by cooperbenson-qz** [comment]
@ndhanushkodi, I just filed #964 adding annotation for the subset of service accounts I feel are most in need of this feature. 

@reza-koneksahealth, and @zachfeldman-koneksahealth, please feel free to take a look and suggest any other service accounts that you require annotations for

**Comment by zachfeldman-koneksahealth** [comment]
@cooperbenson-qz it looks great! I believe this should fix an issue I'm facing. Is there an argument against allowing annotations for the other service accounts (connect-inject and the like) ?

**Comment by cooperbenson-qz** [comment]
> @cooperbenson-qz it looks great! I believe this should fix an issue I'm facing. Is there an argument against allowing annotations for the other service accounts (connect-inject and the like) ?

Not really but I did have issues with some of them which lead me to trying to do the ones that were explicitly called out as being required. I'll speak more to this in a comment on #964

**Comment by ndhanushkodi** [comment]
Closing since #964 was merged.

**Pull request closed without merging**
