### PR TITLE
use consul server service instead of local agent

### PR DESCRIPTION
**Pull request by grzegorzlyczba**
allows to use sync in setup with servers only

### CODE REVIEW

**Comment by justinwalz** [comment]
I just made the same change locally - then checked PRs to see if someone had the same idea. Can we please get this merged? 

Going to tag @adilyse as you're the top contributor for the project.

**Comment by lkysow** [comment]
Hi @soymo can you describe why you need this change?

We always recommend applications (including our own sync) talk to the local agent because otherwise performance issues arise.

**Comment by justinwalz** [comment]
I can speak for soymo, but our use case is that we're only running consul in order to sync services with the k8s sync project. It's overkill for us to run a client on every node (especially for large clusters), so we prefer to just hit the three servers directly via the k8s service.

**Comment by lkysow** [comment]
Thanks for the reply Justin.
A follow-up: which way are you syncing, consul => kubernetes or kubernetes => consul. Also do you have Consul servers and clients running outside of Kubernetes? Or are your servers only in Kubernetes and your clients are all outside of Kubernetes and using the Consul servers in Kube?

**Comment by justinwalz** [comment]
We are syncing kubernetes => consul.

We use the consul service registry + consul-template to generate nginx upstreams for a reverse proxy we run. The kubernetes servers are in k8s, via this helm chart. The only user of this setup is the proxy using consul-template, no consul agents running in client mode.

**Comment by lkysow** [comment]
Hi @grzegorzlyczba, thanks for the PR! This is now supported without the extra setting. If clients are `false` then we will automatically use the servers for sync catalog. So we're going to close this PR for now. Happy to re-open if this doesn't work for your use case.

**Pull request closed without merging**
