### PR TITLE
Add readiness probe params to client (#1)

### PR DESCRIPTION
**Pull request by dianazv**
* add readinessProbe parameters for client daemonSet template

* add readinessProbe parameters for client daemonSet template

* remove conditionaks from readinessProbe

* add examples for readinessProbe

### CODE REVIEW

**Comment by dianazv** [comment]
Hi @lkysow - wanted to ping you kindly and ask what is the status of the pr and see if there is anything else I can add. Thanks!

**Comment by kschoche** [comment]
Hi! thank you for submitting this PR!
I think maybe it would be clearer to provide these as default settings to the client-daemonset similar to how it is done in the server-statefulset template?  This would allow you to override it in your own values file as well.
Since it is the same readinessProbe in each template they could use the same defaults.

```
diff --git a/templates/client-daemonset.yaml b/templates/client-daemonset.yaml
index 9c5fa9f..f9e62ac 100644
--- a/templates/client-daemonset.yaml
+++ b/templates/client-daemonset.yaml
@@ -301,6 +301,11 @@ spec:
                   curl http://127.0.0.1:8500/v1/status/leader \
                   {{- end }}
                   2>/dev/null | grep -E '".+"'
+            failureThreshold: 2
+            initialDelaySeconds: 5
+            periodSeconds: 3
+            successThreshold: 1
+            timeoutSeconds: 5
           {{- if .Values.client.resources }}
           resources:
             {{- if eq (typeOf .Values.client.resources) "string" }}
```

I've tested this out and it has the added benefit of increasing the period from kubernetes default of 1s to 3s so that we're not probing 3x more often than for the servers.

Thoughts?

**Comment by dianazv** [comment]
Hi, thanks for your comment!
So if I understand you correctly, then I should add defaults to the client-daemonset template as in the server-statefulset template. But if I don't add a check in the template to see if these parameters exist in my values file as well how can I override them?
Thanks!

**Comment by dianazv** [comment]
hi, wanted to make sure you read my last comment, thanks

**Comment by elcomtik** [comment]
This would be great enhancement for me, I would appreciate it if this PR was merged.

**Comment by lkysow** [comment]
Hi @dianazv and @elcomtik,
Sorry, looks like this one fell through the cracks. @dianazv I think this is what we'd suggested:

In `values.yaml`:
```yaml
server:
  # YAML template string specifying the readiness probe.
  # This string can contain Helm template statements.
  readinessProbe: |
    exec:
      command:
        - "/bin/sh"
        - "-ec"
        - |
          {{- if .Values.global.tls.enabled }}
          curl \
            --cacert /consul/tls/ca/tls.crt \
            https://127.0.0.1:8501/v1/status/leader \
          {{- else }}
          curl http://127.0.0.1:8500/v1/status/leader \
          {{- end }}
          2>/dev/null | grep -E '".+"'
    failureThreshold: 2
    initialDelaySeconds: 5
    periodSeconds: 3
    successThreshold: 1
    timeoutSeconds: 5
```

And then in `server-statefulset.yaml`:
```yaml
          readinessProbe:
            {{ tpl .Values.server.readinessProbe . | nindent 12 | trim }}
```

We'd do the same for the client helm values.

**Comment by t-eckert** [comment]
Thank you for your pull request! The contents of this repository have been merged into [`hashicorp/consul-k8s`](https://github.com/hashicorp/consul-k8s) under the `charts/consul` directory. Please follow the instructions [here](https://github.com/hashicorp/consul-helm/issues/1051) to migrate your pull request to the `consul-k8s` repository.
This PR will now be closed and the `consul-helm` repository archived to avoid confusion between the old and new repositories.

**Pull request closed without merging**
