### PR TITLE
Fix artifacthub annotations

### PR DESCRIPTION
**Pull request by ndhanushkodi**
Changes proposed in this PR:
- Indented the multiline string. It was rendering as keys before, which made the chart invalid yaml. [Acceptance test failure](https://circleci.com/gh/hashicorp/consul-helm/11435)

How I've tested this PR:
Acceptance tests locally

How I expect reviewers to test this PR:
Acceptance test on this branch, review

### CODE REVIEW

**Review by ishustava — APPROVED** [review]
🙏

**Review by kschoche — APPROVED** [review]
👍🏽

**Review by lkysow — APPROVED** [review]
🙏

**Review by thisisnotashwin — APPROVED** [review]
🙏

**Pull request merged**
