### PR TITLE
Add ability to set extra labels on client pods

### PR DESCRIPTION
**Pull request by hamishforbes**
Same as #553 but for the client daemonset pods

### CODE REVIEW

**Review by lkysow — APPROVED** [review]
LGTM

**Comment by hamishforbes** [comment]
Any chance of this being merged now? It's been approved for quite a while

**Comment by ishustava** [comment]
Hey @hamishforbes, sorry for the delay!

I think this is good to go if you have a moment to fix the conflicts.

**Comment by hamishforbes** [comment]
Sure!
Rebased and added type hint to the comment

**Review by ishustava — APPROVED** [review]
Thanks so much for the contribution!

**Pull request merged**
